AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aurora-data-api-sample

  Sample SAM Template for aurora-data-api-sample

Globals:
  Function:
    Timeout: 3

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: SampleApi
      StageName: dev
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_user/
      Handler: app.handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get
            RestApiId:
              Ref: ApiGateway
