AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aurora-data-api-sample

  Sample SAM Template for aurora-data-api-sample

Globals:
  Api:
    OpenApiVersion: 3.0.2
  Function:
    Timeout: 10
    Environment:
      Variables:
        RDS_ARN: !GetAtt DbCluster.DBClusterArn
        SECRET_ARN: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aurora-data-api-sample-kD4ITI"
        DATABASE_NAME: !Ref DatabaseName

Parameters:
  DbUsername:
    Type: String
  DbPassword:
    Type: String
    NoEcho: true
  DatabaseName:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: SampleApi
      StageName: dev
  DBLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
      ContentUri: src/layers/db
      Description: DB Layer
      LayerName: DBLayer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9
  Boto3Layer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
      ContentUri: src/layers/boto3
      Description: boto3 Layer
      LayerName: Boto3Layer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9
  DbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: test-db
      EnableHttpEndpoint: true
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: 5.7.mysql_aurora.2.07.1
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      DatabaseName: !Ref DatabaseName
      ScalingConfiguration:
        MinCapacity: 1
        AutoPause: true
        MaxCapacity: 1
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: AuroraDataApiSamplePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - rds-data:ExecuteStatement
                  - rds-data:RollbackTransaction
                  - rds-data:CommitTransaction
                  - rds-data:BatchExecuteStatement
                  - rds-data:BeginTransaction
                Resource: !GetAtt DbCluster.DBClusterArn
              - Effect: "Allow"
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:aurora-data-api-sample-kD4ITI"
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/api/get_user/
      Handler: app.handler
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Layers:
        - !Ref DBLayer
        - !Ref Boto3Layer
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{name}
            Method: get
            RestApiId:
              Ref: ApiGateway
