AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  aurora-data-api-sample

  Sample SAM Template for aurora-data-api-sample

Globals:
  Function:
    Timeout: 3

Parameters:
  DbMasterUsername:
    Type: String
  DbMasterUserPassword:
    Type: String

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: SampleApi
      StageName: dev
  DBLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      CompatibleArchitectures:
        - x86_64
      CompatibleRuntimes:
        - python3.9
      ContentUri: layers/db
      Description: DB Layer
      LayerName: DBLayer
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.9
  DbCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: test-db
      EnableHttpEndpoint: true
      Engine: aurora-mysql
      EngineMode: serverless
      EngineVersion: 5.7.mysql_aurora.2.07.1
      MasterUsername: !Ref DbMasterUsername
      MasterUserPassword: !Ref DbMasterUserPassword
      DatabaseName: Users
      ScalingConfiguration:
        MinCapacity: 1
        AutoPause: true
        MaxCapacity: 1
  GetUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: get_user/
      Handler: app.handler
      Runtime: python3.9
      Layers:
        - !Ref DBLayer
      Architectures:
        - x86_64
      Events:
        GetUser:
          Type: Api
          Properties:
            Path: /user/{id}
            Method: get
            RestApiId:
              Ref: ApiGateway
